### ISSUE TITLE
Design Code Review

### ISSUE THREAD

**Issue by nikofenev** [agujaIvan/visitorCheckInWebApp#3]
# Design/Code Review 1

### Reviewer: *Nikolay Fenev*

|Item |Criteria|Rating | Comments/Suggestions|
|--------|---------|---------------|---|
||| Use the following scale:<br> 1= It needs more work<br>  2 = Somewhat<br> 3 = Yes it is great|Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| 2 | *The problem statement is described well. There are some typos, I would suggest running the whole text through MS WORD, that will reduce typos. And I believe the problem statement is too long, if you consolidate it will be easier to read.*|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |2 | *The design looks good, but it's not full. I saw it on your local machine and it looks good, but if you push all the screens so it is full, that will help. And the application flow is not fully completed so I would suggest doing that as well.*
|**Data model**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>|2| *The datamodel is good, there is just one table that has a lot of foreign keys and that could be reduced. listOfVisitorTable.* 
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. | 1 | Project structure is good on your local machine, I would suggest push everything to your repository.

**Comment by agujaIvan** [comment]
I believe in the code the CRUD is complete, maybe you didnt look well on that part, thanks for your comments!

**Comment by nikofenev** [comment]
I think I got confused I will go ahead and edit it. Thanks Ivan.
