### ISSUE TITLE
Instructor Feedback - Week 4 Exercise - Hibernate Dao

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [agujaIvan/visitorCheckInWebApp#4]
Looks like you have a good start with Hibernate and daos.  Nice job with logging and use of the equals override on entities to allow for easy comparison in your unit tests.

- [ ] For a known set of values like Status or Gender, it may make sense for these to be an Enumeration. The https://github.com/MadJavaEntFall2017/HibernateDemo has an example of this.
- [ ] Now that you have a few daos created, you've probably noticed these could get pretty redundant with each having a get, update, add, delete, etc. Check out my post on Slack #hibernate from earlier today regarding the generic dao which will save you a  lot of time and lines of code!

**Comment by agujaIvan** [comment]
I will try to use a generic dao on a few tables and the enumerations as well, thank you for your suggestions.
