### ISSUE TITLE
Design/Code Review 1

### ISSUE THREAD

**Issue by asommer123** [agujaIvan/visitorCheckInWebApp#5]
# Design/Code Review 1

### Reviewer: Anthony Sommer

|Item |Criteria|Rating | Comments/Suggestions|
|--------|---------|---------------|---|
||| Use the following scale:<br> 1= It needs more work<br>  2 = Somewhat<br> 3 = Yes it is great|Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| 3 | Explains very well the problem and solution with your web app.  There are a few typos.  For example "is to know the crowed" could be "is to know if it is crowded". Great use of picture as well! |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | 2 | Fairly logical flow of screens.  There were some suggestions Niko and I made during your overview that might help (if there is time to add them).|
|**Data model**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| 2 | Great start on the database.  Biggest suggestion I would make is to remove all the foreign keys as you can move through tables without having everything connected directly.|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.| 1 | I didn't see the code out in your repository.

**Comment by agujaIvan** [comment]
I have another branch called intelliJ, there you should be able to see the code, Im gonna be doing some updates over this weekend on the code as well. thanks for you comments
