### ISSUE TITLE
Checkpoint 2 - Instructor Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [agujaIvan/visitorCheckInWebApp#6]
- [ ] Nice job keeping up with your time log.
- [ ] If you are not using the journal, remove it.
- [ ] Looks like your started off strong with your project plan - be sure to update this with what you have completed, and build out the remaining weeks, as you should have a good picture of what you'll be working on from here on it. REST will be the last new technology that you need to implement in your project. 
- [ ] It looks like you chose a weather service of your service/api, how will this be used in the application? I don't see it represented on the wireframes?
- [ ] How is research going into angular? Where does this fall in your project plan?

**Comment by agujaIvan** [comment]
I might change the weather api for something else, Im not sure yet I will be updating this on the next coming week, thanks for your observations.
