### ISSUE TITLE
Final Code Review

### ISSUE THREAD

**Issue by brookeswanson** [agujaIvan/visitorCheckInWebApp#9]
# Design/Code Review 3

#### Reviewer: Brooke Swanson

| Category | Criteria | Rating/Comments| 
|--------|---------|---------------|
|**Project Overview**|| |
|| Which planned functionality has been met? | You can register users, sign in, register for classes, and create new classes.  It looks all of the functionality has been met. |
|| What planned functionality has not been met? | I don't see any functionality that was intended to be implemented that isn't currently. |
||Describe the GitHub history and what it demonstrates about the project progress during the semester.| The commit count was small for a big project, but it's difficult to keep up with the commits when working in bursts. |
||Describe how peer and instructor feedback/recommendations were incorporated into the project.|I did not find the feedback/recommendations in order to compare the before and after of this project. |
||Other comments/notes?| There was not .gitignore included so everything has been committed, and although that made getting the project up and running fairly simple it also means the git repository is relatively bloated. I think intelliJ has some built in gitignore options that does most of the work for you. |
|**JSPs**|| |
||Evaluate the JSPs for templating, business logic, data validation, overall look and feel.| The yellow for the login form is really bright and could probably be a less intense color. |
||Other comments/notes?| Your jsps are really well organized and thorough. Using a javascript/jquery plugin for data validation would allow you to provide useful error handling and messages without adding a lot of Java logic. |
|**Java code quality**|Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number) <li>single-purpose methods <li>well-structured project <li>descriptive naming of packages, classes, methods, variables <li>classes appropriately-sized  (no monster classes) <li> CPD (copy paste detection, meaning are the same lines of code repeated?) <li>are there candidates for super/subclass relationships, abstract classes, interfaces? <li>are any values hard-coded that should be in a properties file? <li>proper exception handling <li>proper error reporting to the user <li> code documentation |CreateLessonServlet lines 25 -60 are fairly repeditive.  If you are submitting a form with checkboxes you could probably just directly save it to an array and use .filter in order to get the checked boxes. UserServlet.createAndStoreUser has a ton of parameters and is hard to read.  In addition you set a lot of attributes for the user, you might consider just adding a method to the user class that sets that userdata for you|Other comments/notes?| |
|**Logging**|Evaluate the use of logging, for example:<li>appropriate use of logging statements in the code for error logging and debugging <li>logging levels used - info, debug, error <li> no occurrences of  System.out.printlns or printStackTrace() <li> logging works on AWS deploy|Logging is working everywhere including when i temporarily deployed to AWS. There are not print stack trace and the log levels are what I would expect.|Other comments/notes?||
|**Unit Tests**|Evaluate the unit tests, for example: <li>tests are truly a unit test rather than a high level functional test <li>test data is appropriately cleaned up or handled <li> there is full coverage of methods that perform business logic or utility functions <li>redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After|I could have missed it but there is only one unit test.  The code coverage is pretty low considering the amount of java classes are utilized. |Other comments/notes?| This is only semi-related to testing, but you can use a package other than edu.matc.  It doesn't matter, but if you own a domain it might be worth using that instead (on future projects)|
|**Security**|Evaluate authentication/authorization:| |
||Is it implemented correctly and working locally as well as on AWS?|It is implemented correctly and working both locally and on AWS.|Other comments/notes?| |
|**Web Service/API integration**|Evaluate the service/api integration, for example: <li> Which service/api is implemented? <li>How is  error handling of the service implemented? For example, what happens if the service is not available?|I'm not sure what API was integrated.  I will reach out to Ivan for this as well, and can re-evaluate once I have a better idea of what I am looking for.|
||Other comments/notes?| |
|**Independent research topic**| What is the independent research topic?|Ibatis framework.  |
||Is the independent research topic/technique implemented in the project?|It is implemented correctly and the functionality looks potentially easier than hibernate to use.  Good choice of topic- I struggled with hibernate a lot throughout my project so finding other options is great. |
||Other comments/notes?| |
|**Deployment**| Has the application been successfully deployed to AWS or another hosting service?| I did not see where this was deployed. I will try and get in contact with Ivan sometime tomorrow and will provide further feedback. |
||Is the hosted application fully functioning?| I believe as long as the ec2 instance was set up properly that the application should be fully functional.  It functioned pretty seamlessly locally and it only really took 5 minutes to get setup and I was able to deploy the war to my own ec2 instance temporarily to check functionality. |
||Other comments/notes?| |

**Comment by pawaitemadisoncollege** [comment]
@bswanson3 RE: prior feedback - there are 8 closed issues here that you could review
